### ISSUE TITLE
能不能加一个网络调用的接口

### ISSUE THREAD

**Issue by mykakaru** [Uahh/Reborn#9]
供群机器人使用，调一下直接返回一次重生结果

**Comment by Uahh** [comment]
如果单纯是要数据的话，你可以把“data/result.json”直接拿去，随机逻辑很好写。

**Comment by Aziteee** [comment]
> > 我用node写了一个api，直接照搬的源码🤣同时可以指定洲，如： https://api.azite.cn/reborn?continent=EU
> > 如果是群机器人的话我也写了一个插件[nonebot_plugin_reborn](https://github.com/Aziteee/nonebot_plugin_reborn)
> 
> 好呀，我可以把api放到readme上吗？

可以啊😀

**Comment by Uahh** [comment]
已加，谢谢
